name: googleapis_auth
version: 0.2.11+1
author: Dart Team <misc@dartlang.org>
description: Obtain Access credentials for Google services using OAuth 2.0
homepage: https://github.com/dart-lang/googleapis_auth
environment:
  sdk: '>=2.0.0-dev.56.0 <3.0.0'

dependencies:
  crypto: '>=0.9.2 <3.0.0'
  http: '>=0.11.3+17 <0.13.0'

dev_dependencies:
  test: ^1.3.0
